[package]
name = "hmm-pinyin-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinyin = "0.9.0"
redb = "0.13.0"
regex = "1.7.1"
itertools = "0.10.5"
serde_json = "1.0"
